import java.util.Scanner;

public class Alg7 {


  public static void main(String[] args){

	Scanner ler = new Scanner(System.in);

	int = a = 30;
    int = b = 15;
    int = ValSubtração;
    int = ValMultiplicação;

    	ValSubtração = a-b;
    	ValMultiplicação = a+b;

    	System.out.println ( "O valor da adição é" + ValSubtração );
    	System.out.println ( "O valor da adição é" + ValMultiplicação );

  }

}